apiVersion: apps/v1
kind: Deployment
metadata:
  name: shift-portal
  namespace: shift-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shift-portal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: shift-portal
    spec:
      containers:
      - name: shift-portal
        image: grc.io/PROJECT_ID/REPOSITORY/IMAGE:TAG
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m